require "plugins.config.cmp"
require "plugins.config.navic"
require "plugins.config.lsp-inlayhints"
require "plugins.config.lsp"
require "plugins.config.telescope"
require "plugins.config.treesitter"
require "plugins.config.autopairs"
require "plugins.config.comment"
-- require "plugins.config.gitsigns"
require "plugins.config.nvimtree"
require "plugins.config.lualine"
require "plugins.config.bufferline"
require "plugins.config.nvterm"
require "plugins.config.project"
require "plugins.config.impatient"
require "plugins.config.indentline"
require "plugins.config.alpha"
require "plugins.config.surround"
require "plugins.config.whichkey"
require "plugins.config.hop"
require "plugins.config.colorizer"
-- require "plugins.config.zen-mode"
-- require "plugins.config.git-blame"
-- require "plugins.config.gist"
-- require "plugins.config.gitlinker"
require "plugins.config.notify"
require "plugins.config.dap"
require "plugins.config.cybu"
require "plugins.config.winbar"
require "plugins.config.devicons"
require "plugins.config.harpoon"

local colorscheme = "onedark"
local theme = require "plugins.config.theme"
theme.init(onenord)
